Repository GSM-MSG/GCMS-BackEnd, pull requests merged in 2023-03, with the labels that each got.

#124 🔀 :: 123-동아리 상태 추가
  src/main/kotlin/com/msg/gcms/domain/club/domain/entity/Club.kt
  src/main/kotlin/com/msg/gcms/domain/club/enums/ClubStatus.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#127 🔀 :: 118 - 이미지 개수 수정
  src/main/kotlin/com/msg/gcms/domain/image/utils/impl/ImageValidatorImpl.kt
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#133 🚑 :: 132 - 동아리 생성 수정
  src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#135 🔀 :: 134 - 토큰 재발급 조건식 수정
  src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
  src/main/kotlin/com/msg/gcms/global/security/jwt/JwtTokenProvider.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#138 🔀 :: 126 - 동아리 구성원을 엑셀로 출력하는 API
  build.gradle.kts
  src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt
  src/main/kotlin/com/msg/gcms/domain/admin/service/CreateClubMemberExcelByClassNumService.kt
  src/main/kotlin/com/msg/gcms/domain/admin/service/CreateClubMemberExcelService.kt
  src/main/kotlin/com/msg/gcms/domain/admin/service/impl/CreateClubMemberExcelByClassNumServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/admin/service/impl/CreateClubMemberExcelServiceImpl.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
  src/main/kotlin/com/msg/gcms/global/util/ExcelUtil.kt
  src/main/kotlin/com/msg/gcms/global/util/impl/ExcelUtilImpl.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#137 🔀 :: 136 - ci 수정
  .github/workflows/ci.yml
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#131 🔀 :: 130 - 동아리 수락 API 구현
  src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt
  src/main/kotlin/com/msg/gcms/domain/admin/service/AcceptClubService.kt
  src/main/kotlin/com/msg/gcms/domain/admin/service/impl/AcceptClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#129 🔀 :: 128-동아리 리스트 로직 수정
  src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/FindClubListServiceImpl.kt
  src/test/kotlin/com/msg/gcms/domain/club/service/FindClubListServiceTest.kt
  src/test/kotlin/com/msg/gcms/testUtils/ClubDataUtil.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple

#142 🔀 :: 141 - hasRole로 변경
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#145 🔀 ::144 - 동아리 생성 거절 API
  src/main/kotlin/com/msg/gcms/domain/admin/exception/ClubStatusNotPendingException.kt
  src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt
  src/main/kotlin/com/msg/gcms/domain/admin/service/RejectClubService.kt
  src/main/kotlin/com/msg/gcms/domain/admin/service/impl/RejectClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#147 🔀 :: 146 - 생성 대기중인 동아리 리스트 API
  src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt
  src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/dto/PendingClubDto.kt
  src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/request/.gitKeep
  src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/response/PendingClubResponse.kt
  src/main/kotlin/com/msg/gcms/domain/admin/service/FindPendingClubListService.kt
  src/main/kotlin/com/msg/gcms/domain/admin/service/impl/FindPendingClubListServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/admin/util/AdminConverter.kt
  src/main/kotlin/com/msg/gcms/domain/admin/util/impl/AdminConverterImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#150 🔀 :: 신청대기 동아리 리스트에 clubId값 추가
  src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/dto/PendingClubDto.kt
  src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/response/PendingClubResponse.kt
  src/main/kotlin/com/msg/gcms/domain/admin/util/impl/AdminConverterImpl.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple

#152 🔀 :: 동아리 거절 API URL 수정
  src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#155 🔀 :: 154 - 토큰 시간 조절
  src/main/kotlin/com/msg/gcms/global/security/jwt/JwtTokenProvider.kt
  src/main/kotlin/com/msg/gcms/global/security/jwt/properties/TokenTimeProperties.kt
  src/main/resources/application.yml
Labels: 1️⃣ Priority: High, ⚡️ Simple

#158 🔀 :: 157 - 유저페이지 동아리 정보 로직 수정
  src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
  src/main/kotlin/com/msg/gcms/domain/user/service/impl/FindUserServiceImpl.kt
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#160 🔀 :: 159 - 마이페이지 오류
  src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
  src/main/kotlin/com/msg/gcms/domain/user/service/impl/FindUserServiceImpl.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#162 🔀 :: 161 - 다중로그인 되게 변경
  src/main/kotlin/com/msg/gcms/domain/auth/domain/entity/RefreshToken.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#165 🔀 :: 164 - 동아리 수정 로직 변경
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/UpdateClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/utils/ClubConverter.kt
  src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#171 🔀 :: 170 - 동아리 마감 여부 수정
  src/main/kotlin/com/msg/gcms/domain/admin/presentation/data/request/.gitKeep
  src/main/kotlin/com/msg/gcms/domain/club/utils/impl/UpdateClubStatusUtil.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#187 🔀 :: 186 - deviceToken이 없으면 메세지를 보내지 않기
  src/main/kotlin/com/msg/gcms/global/util/impl/MessageSendUtilImpl.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#189 🔀 :: 188 - deviceToken이 없으면 return
  src/main/kotlin/com/msg/gcms/domain/user/exception/DeviceTokenNotFoundException.kt
  src/main/kotlin/com/msg/gcms/global/util/impl/MessageSendUtilImpl.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#197 🔀 :: 동아리 생성 수락 거절 오류
  src/main/kotlin/com/msg/gcms/global/fcm/FcmConfig.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#199 🔀 :: 198 - fcm 오류
  src/main/kotlin/com/msg/gcms/global/fcm/FcmConfig.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#202 🔀 :: 201 - 유저 검색시 어드민 검색 불가로 만들기
  src/main/kotlin/com/msg/gcms/domain/user/service/impl/SearchUserServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/user/utils/UserValidator.kt
  src/main/kotlin/com/msg/gcms/domain/user/utils/impl/UserValidatorImpl.kt
  src/test/kotlin/com/msg/gcms/domain/user/service/SearchUserServiceTest.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor, ⚡️ Simple

#209 🔀 :: 206 - 부장위임 어드민이 할때 이상한거 해결
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/DeleteClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/OpenClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/UpdateClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/service/impl/DelegateHeadServiceImpl.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor, 🐞 Bug

#213 🔀 :: 212 - 엑셀 만드는 로직 수정
  src/main/kotlin/com/msg/gcms/domain/admin/service/impl/CreateClubMemberExcelByClassNumServiceImpl.kt
  src/main/kotlin/com/msg/gcms/global/util/ExcelUtil.kt
  src/main/kotlin/com/msg/gcms/global/util/impl/ExcelUtilImpl.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor, 🐞 Bug

#215 🔀 :: 214-동아리 인원수 엑셀을 가져오는 API
  src/main/kotlin/com/msg/gcms/domain/admin/presentation/AdminController.kt
  src/main/kotlin/com/msg/gcms/domain/admin/service/ClubMemberCountExcelService.kt
  src/main/kotlin/com/msg/gcms/domain/admin/service/impl/ClubMemberCountExcelServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/auth/presentation/AuthController.kt
  src/main/kotlin/com/msg/gcms/domain/auth/presentation/data/request/SignInRequestDto.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#226 🔀 :: 224 - 동아리 제목에 콜론(:)이 들어갈때 엑셀로 뽑으면 에러
  src/main/kotlin/com/msg/gcms/domain/admin/service/impl/CreateClubMemberExcelServiceImpl.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor, 🐞 Bug

#228 🔀 :: 227 - 학번을 학년, 반, 번호로 분리
  src/main/kotlin/com/msg/gcms/domain/admin/service/impl/CreateClubMemberExcelServiceImpl.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple
