Repository GSM-MSG/GCMS-BackEnd, pull requests merged in 2023-01, with the labels that each got.

#2 🔀 :: 1 - 프로젝트 설정
  .idea/workspace.xml
  gcms/.gitignore
  gcms/build.gradle.kts
  gcms/gradle/wrapper/gradle-wrapper.jar
  gcms/gradle/wrapper/gradle-wrapper.properties
  gcms/gradlew
  gcms/gradlew.bat
  gcms/settings.gradle.kts
  gcms/src/main/kotlin/com/msg/gcms/GcmsApplication.kt
  gcms/src/main/resources/application.yml
  gcms/src/test/kotlin/com/msg/gcms/GcmsApplicationTests.kt
Labels: ⚙ Setting

#8 🔀 :: 7- codeowner 추가
  .github/CODEOWNERS
  .idea/workspace.xml
Labels: 1️⃣ Priority: High, ✨ Feature

#6 🔀 :: 5 redis 설정
  .gitignore
  .idea/misc.xml
  .idea/workspace.xml
  src/main/kotlin/com/msg/gcms/GcmsApplication.kt
  src/main/kotlin/com/msg/gcms/global/redis/RedisConfig.kt
  src/main/kotlin/com/msg/gcms/global/redis/properties/RedisProperties.kt
  src/main/resources/application.yml
Labels: 1️⃣ Priority: High, ✨ Feature

#12 🔀 :: 10-ERD에 구현된 엔티티 구현
  src/main/kotlin/com/msg/gcms/domain/applicant/domain/entity/Applicant.kt
  src/main/kotlin/com/msg/gcms/domain/club/domain/entity/ActivityImg.kt
  src/main/kotlin/com/msg/gcms/domain/club/domain/entity/Club.kt
  src/main/kotlin/com/msg/gcms/domain/club/enums/ClubType.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/domain/entity/ClubMember.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/enums/MemberScope.kt
  src/main/kotlin/com/msg/gcms/domain/user/domain/entity/User.kt
Labels: 0️⃣ Priority: Critical

#14 🔀 :: 11-RefreshToken 엔티티 생성
  src/main/kotlin/com/msg/gcms/domain/auth/domain/entity/RefreshToken.kt
Labels: 2️⃣ Priority: Medium

#11 🔀 :: 9-예외처리 설정
  src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
  src/main/kotlin/com/msg/gcms/global/exception/ErrorResponse.kt
  src/main/kotlin/com/msg/gcms/global/exception/exceptions/BasicException.kt
  src/main/kotlin/com/msg/gcms/global/exception/handler/GlobalExceptionHandler.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#16 🔀 :: 15-시큐리티 설정 추가
  src/main/kotlin/com/msg/gcms/domain/user/domain/repository/UserRepository.kt
  src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
  src/main/kotlin/com/msg/gcms/global/security/filter/ExceptionFilter.kt
  src/main/kotlin/com/msg/gcms/global/security/handler/CustomAccessDeniedHandler.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#18 🔀 :: 19-errorCode 수정
  src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#23 🔀 :: 22-현재 로그인한 유저 가져오는 객체
  src/main/kotlin/com/msg/gcms/domain/user/exception/UserNotFoundException.kt
  src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
  src/main/kotlin/com/msg/gcms/global/util/UserUtil.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#27 🔀 :: 21 - 동아리 리스트 api
  .gitignore
  build.gradle.kts
  src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
  src/main/kotlin/com/msg/gcms/domain/club/presentation/ClubController.kt
  src/main/kotlin/com/msg/gcms/domain/club/presentation/data/dto/ClubListDto.kt
  src/main/kotlin/com/msg/gcms/domain/club/presentation/data/dto/ClubTypeDto.kt
  src/main/kotlin/com/msg/gcms/domain/club/presentation/data/request/.gitKeep
  src/main/kotlin/com/msg/gcms/domain/club/presentation/data/response/ClubListResponseDto.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/FindClubListService.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/FindClubListServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/utils/ClubConverter.kt
  src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
  src/test/kotlin/com/msg/gcms/domain/.gitKeep
  src/test/kotlin/com/msg/gcms/domain/club/controller/FindClubListControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/service/FindClubListServiceTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/utils/ClubConverterTest.kt
  src/test/kotlin/com/msg/gcms/testUtils/ClubDataUtil.kt
  src/test/kotlin/com/msg/gcms/testUtils/TestUtils.kt
  src/test/kotlin/com/msg/gcms/testUtils/UserDataUtil.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#29 🔀 :: 24-동아리 생성 API
  src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ActivityImgRepository.kt
  src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
  src/main/kotlin/com/msg/gcms/domain/club/presentation/ClubController.kt
  src/main/kotlin/com/msg/gcms/domain/club/presentation/data/dto/ClubDto.kt
  src/main/kotlin/com/msg/gcms/domain/club/presentation/data/request/CreateClubRequest.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/CreateClubService.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/utils/ClubConverter.kt
  src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/domain/repository/ClubMemberRepository.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
  src/test/kotlin/com/msg/gcms/domain/club/presentation/CreateClubControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImplTest.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#36 🔀 :: 35-유저id binary(16)으로 변경
  src/main/kotlin/com/msg/gcms/domain/user/domain/entity/User.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug
