Repository GSM-MSG/GCMS-BackEnd, pull requests merged in 2023-02, with the labels that each got.

#37 ⚙️ :: 34-ci 구축
  .github/workflows/ci.yml
  src/test/kotlin/com/msg/gcms/GcmsApplicationTests.kt
  src/test/kotlin/com/msg/gcms/domain/club/controller/CreateClubControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/service/CreateClubServiceImplTest.kt
Labels: 2️⃣ Priority: Medium

#40 🔀 :: 39-ClubMember에 Scope가 불필요해 삭제
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/domain/entity/ClubMember.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/domain/entity/enums/MemberScope.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/enums/MemberScope.kt
Labels: 1️⃣ Priority: High

#43 🔀 :: 유저 정보 가져오기 API
  src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/domain/repository/ClubMemberRepository.kt
  src/main/kotlin/com/msg/gcms/domain/user/presentaion/UserController.kt
  src/main/kotlin/com/msg/gcms/domain/user/presentaion/data/dto/UserDto.kt
  src/main/kotlin/com/msg/gcms/domain/user/presentaion/data/request/.gitKeep
  src/main/kotlin/com/msg/gcms/domain/user/presentaion/data/response/UserResponseDto.kt
  src/main/kotlin/com/msg/gcms/domain/user/service/FindUserService.kt
  src/main/kotlin/com/msg/gcms/domain/user/service/impl/FindUserServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/user/utils/UserConverter.kt
  src/main/kotlin/com/msg/gcms/domain/user/utils/impl/UserConverterImpl.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
  src/test/kotlin/com/msg/gcms/domain/user/controller/FindUserControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/user/service/FindUserServiceTest.kt
  src/test/kotlin/com/msg/gcms/testUtils/ClubDataUtil.kt
  src/test/kotlin/com/msg/gcms/testUtils/UserDataUtil.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#26 🔀 :: 23-구현체와 인터페이스 리팩토링
  src/main/kotlin/com/msg/gcms/domain/auth/util/AuthConverter.kt
  src/main/kotlin/com/msg/gcms/domain/auth/util/impl/AuthConverterImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/domain/entity/Club.kt
  src/main/kotlin/com/msg/gcms/domain/user/domain/entity/User.kt
  src/test/kotlin/com/msg/gcms/domain/auth/util/AuthConverterTest.kt
  src/test/kotlin/com/msg/gcms/testUtils/AuthDataUtil.kt
  src/test/kotlin/com/msg/gcms/testUtils/TestUtils.kt
Labels: 2️⃣ Priority: Medium

#46 🔀 :: 44-동아리 신청 마감 API
  src/main/kotlin/com/msg/gcms/domain/club/presentation/ClubController.kt
  src/main/kotlin/com/msg/gcms/domain/club/presentation/data/dto/ClubStatusDto.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/CloseClubService.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/CloseClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/utils/ClubConverter.kt
  src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
  src/test/kotlin/com/msg/gcms/domain/club/controller/CloseClubControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/controller/CreateClubControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/controller/FindClubListControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/controller/UpdateClubControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/service/CloseClubServiceTest.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#28 🔀 :: 17-동아리 멤버 리스트 조회 API
  src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
  src/main/kotlin/com/msg/gcms/domain/club/exception/ClubNotFoundException.kt
  src/main/kotlin/com/msg/gcms/domain/club/presentation/ClubController.kt
  src/main/kotlin/com/msg/gcms/domain/club/presentation/data/dto/ClubDto.kt
  src/main/kotlin/com/msg/gcms/domain/club/utils/ClubConverter.kt
  src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/domain/repository/ClubMemberRepository.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/enums/MemberScope.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/exception/ClubMemberNonExistentException.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/presentation/ClubMemberController.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/presentation/data/response/ClubMemberListDto.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/presentation/data/response/ClubMemberListResponse.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/service/FindClubMemberListService.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/service/impl/FindClubMemberListServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/util/ClubMemberConverter.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/util/impl/ClubMemberConverterImpl.kt
  src/main/kotlin/com/msg/gcms/domain/user/presentaion/data/dto/UserDto.kt
  src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
  src/main/kotlin/com/msg/gcms/global/security/auth/AuthDetailsService.kt
  src/test/kotlin/com/msg/gcms/domain/club/controller/CloseClubControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/service/CreateClubServiceImplTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/service/FindClubListServiceTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/service/UpdateClubServiceImplTest.kt
  src/test/kotlin/com/msg/gcms/domain/clubmember/controller/FindClubMemberListControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/clubmember/service/FindClubMemberListTest.kt
  src/test/kotlin/com/msg/gcms/testUtils/ClubDataUtil.kt
  src/test/kotlin/com/msg/gcms/testUtils/ClubMemberDataUtil.kt
  src/test/kotlin/com/msg/gcms/testUtils/TestUtils.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#53 🔀 :: 52 - 이미지 업로드 API
  build.gradle.kts
  src/main/kotlin/com/msg/gcms/domain/image/exception/FailUploadImageException.kt
  src/main/kotlin/com/msg/gcms/domain/image/exception/FileSizeOverException.kt
  src/main/kotlin/com/msg/gcms/domain/image/presentation/ImageController.kt
  src/main/kotlin/com/msg/gcms/domain/image/presentation/data/dto/ImagesDto.kt
  src/main/kotlin/com/msg/gcms/domain/image/presentation/data/dto/UploadImagesDto.kt
  src/main/kotlin/com/msg/gcms/domain/image/presentation/data/request/.gitKeep
  src/main/kotlin/com/msg/gcms/domain/image/presentation/data/response/ImagesResponseDto.kt
  src/main/kotlin/com/msg/gcms/domain/image/service/UploadImageService.kt
  src/main/kotlin/com/msg/gcms/domain/image/service/impl/UploadImageServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/image/utils/ImageConverter.kt
  src/main/kotlin/com/msg/gcms/domain/image/utils/ImageValidator.kt
  src/main/kotlin/com/msg/gcms/domain/image/utils/impl/ImageConverterImpl.kt
  src/main/kotlin/com/msg/gcms/domain/image/utils/impl/ImageValidatorImpl.kt
  src/main/kotlin/com/msg/gcms/global/config/s3/S3Config.kt
  src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
  src/main/resources/application.yml
  src/test/kotlin/com/msg/gcms/domain/image/controller/UploadImagesControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/image/service/ImageUploadServiceTest.kt
  src/test/kotlin/com/msg/gcms/domain/image/utils/ImageValidatorTest.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#61 🔀 :: 60 - 동아리 상세페이지 API
  src/main/kotlin/com/msg/gcms/domain/applicant/domain/repository/ApplicantRepository.kt
  src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ActivityImgRepository.kt
  src/main/kotlin/com/msg/gcms/domain/club/enums/Scope.kt
  src/main/kotlin/com/msg/gcms/domain/club/presentation/ClubController.kt
  src/main/kotlin/com/msg/gcms/domain/club/presentation/data/dto/DetailClubDto.kt
  src/main/kotlin/com/msg/gcms/domain/club/presentation/data/response/DetailClubResponseDto.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/DetailClubService.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/DetailClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/utils/ClubConverter.kt
  src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/domain/repository/ClubMemberRepository.kt
  src/main/kotlin/com/msg/gcms/domain/user/domain/repository/UserRepositoryCustom.kt
  src/main/kotlin/com/msg/gcms/domain/user/domain/repository/impl/UserRepositoryCustomImpl.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
  src/test/kotlin/com/msg/gcms/domain/club/controller/CloseClubControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/controller/CreateClubControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/controller/ExitClubControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/controller/FindClubListControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/controller/OpenClubControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/controller/UpdateClubControllerTest.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#67 🔀 :: 66 - 부장 위임 API
  src/main/kotlin/com/msg/gcms/domain/clubMember/presentation/ClubMemberController.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/presentation/data/dto/ChangeHeadDto.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/presentation/data/dto/DelegateHeadDto.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/presentation/data/request/DelegateHeadRequest.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/service/DelegateHeadService.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/service/impl/DelegateHeadServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/util/ClubMemberConverter.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/util/UpdateClubHeadUtil.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/util/impl/ClubMemberConverterImpl.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
  src/test/kotlin/com/msg/gcms/domain/clubmember/controller/DelegateHeadControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/clubmember/controller/FindClubMemberListControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/clubmember/service/DelegateHeadServiceTest.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#65 🔀 :: 64- cd 구축
  .github/workflows/deploy.yml
Labels: 2️⃣ Priority: Medium, 🌏 Deploy

#59 🔀 :: 56-유저탈퇴 API
  src/main/kotlin/com/msg/gcms/domain/applicant/domain/entity/Applicant.kt
  src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/domain/entity/ClubMember.kt
  src/main/kotlin/com/msg/gcms/domain/user/exception/UserIsHeadException.kt
  src/main/kotlin/com/msg/gcms/domain/user/presentaion/UserController.kt
  src/main/kotlin/com/msg/gcms/domain/user/service/WithdrawUserService.kt
  src/main/kotlin/com/msg/gcms/domain/user/service/impl/UpdateProfileImgServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/user/service/impl/WithdrawUserServiceImpl.kt
  src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
  src/test/kotlin/com/msg/gcms/domain/user/controller/FindUserControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/user/controller/SearchUserControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/user/controller/UpdateProfileImgControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/user/controller/WithdrawUserControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/user/service/WithdrawUserServiceTest.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#71 🔀 :: 64-로그인 테스틐 코드 작성
  build.gradle.kts
  src/main/kotlin/com/msg/gcms/domain/auth/service/impl/SignInServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/auth/util/AuthUtil.kt
  src/main/kotlin/com/msg/gcms/domain/auth/util/impl/AuthUtilImpl.kt
  src/main/kotlin/com/msg/gcms/global/gAuth/GAuthConfig.kt
  src/test/kotlin/com/msg/gcms/domain/auth/controller/SignInControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/auth/service/SignInServiceTest.kt
  src/test/kotlin/com/msg/gcms/testUtils/AuthDataUtil.kt
Labels: 1️⃣ Priority: High

#75 🔀 :: 72-동아리 신청 API
  src/main/kotlin/com/msg/gcms/domain/applicant/domain/repository/ApplicantRepository.kt
  src/main/kotlin/com/msg/gcms/domain/applicant/exception/AlreadyClubMemberException.kt
  src/main/kotlin/com/msg/gcms/domain/applicant/exception/DuplicateClubTypeApplicantException.kt
  src/main/kotlin/com/msg/gcms/domain/applicant/presentation/ApplicantController.kt
  src/main/kotlin/com/msg/gcms/domain/applicant/presentation/data/dto/ClubApplyDto.kt
  src/main/kotlin/com/msg/gcms/domain/applicant/repository/ApplicantRepository.kt
  src/main/kotlin/com/msg/gcms/domain/applicant/service/ClubApplyService.kt
  src/main/kotlin/com/msg/gcms/domain/applicant/service/impl/ClubApplyServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/applicant/util/ApplicantSaveUtil.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/DetailClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/domain/repository/ClubMemberRepository.kt
  src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
  src/test/kotlin/com/msg/gcms/domain/applicant/controller/ClubApplyControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/applicant/service/ClubApplyServiceTest.kt
  src/test/kotlin/com/msg/gcms/testUtils/ClubDataUtil.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#78 🔀 :: 69-이슈터져있던 것들 다 수정
  src/main/kotlin/com/msg/gcms/domain/auth/presentation/data/response/SignInResponseDto.kt
  src/main/kotlin/com/msg/gcms/domain/auth/service/impl/SignInServiceImpl.kt
  src/main/kotlin/com/msg/gcms/global/gauth/GAuthConfig.kt
  src/main/kotlin/com/msg/gcms/global/gauth/properties/GAuthProperties.kt
  src/main/kotlin/com/msg/gcms/global/security/auth/AuthDetailsService.kt
  src/test/kotlin/com/msg/gcms/domain/auth/service/SignInServiceTest.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#79 🔀 :: 70 - 커스텀 어노테이션 구현
  src/main/kotlin/com/msg/gcms/domain/auth/presentation/AuthController.kt
  src/main/kotlin/com/msg/gcms/domain/club/presentation/ClubController.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/presentation/ClubMemberController.kt
  src/main/kotlin/com/msg/gcms/domain/image/presentation/ImageController.kt
  src/main/kotlin/com/msg/gcms/domain/user/presentaion/UserController.kt
  src/main/kotlin/com/msg/gcms/global/annotation/RequestController.kt
Labels: 3️⃣ Priority: Low, ♻️ Refactor

#81 🔀 :: 80 - 동아리가 이미 존재하는지 확인하는 로직추가
  src/main/kotlin/com/msg/gcms/domain/club/domain/repository/ClubRepository.kt
  src/main/kotlin/com/msg/gcms/domain/club/exception/ClubAlreadyExistsException.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple

#87 🔀 :: 86-로그아웃 기능 구현
  src/main/kotlin/com/msg/gcms/domain/auth/domain/repository/RefreshTokenRepository.kt
  src/main/kotlin/com/msg/gcms/domain/auth/presentation/AuthController.kt
  src/main/kotlin/com/msg/gcms/domain/auth/service/LogoutService.kt
  src/main/kotlin/com/msg/gcms/domain/auth/service/impl/LogoutServiceImpl.kt
  src/test/kotlin/com/msg/gcms/domain/auth/controller/GetNewRefreshTokenControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/auth/controller/LogoutControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/auth/controller/SignInControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/auth/service/LogoutServiceTest.kt
  src/test/kotlin/com/msg/gcms/testUtils/AuthDataUtil.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#89 🔀 :: 88 - 유저 미니 프로필 API
  src/main/kotlin/com/msg/gcms/domain/user/presentaion/UserController.kt
  src/main/kotlin/com/msg/gcms/domain/user/presentaion/data/dto/UserProfileDto.kt
  src/main/kotlin/com/msg/gcms/domain/user/presentaion/data/response/UserProfileResponseDto.kt
  src/main/kotlin/com/msg/gcms/domain/user/service/FindUserProfileService.kt
  src/main/kotlin/com/msg/gcms/domain/user/service/impl/FindUserProfileServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/user/utils/UserConverter.kt
  src/main/kotlin/com/msg/gcms/domain/user/utils/impl/UserConverterImpl.kt
  src/test/kotlin/com/msg/gcms/domain/user/controller/FindUserControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/user/controller/SearchUserControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/user/controller/UpdateProfileImgControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/user/controller/WithdrawUserControllerTest.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#93 🔀 :: 92 - uuid 전략 수정
  src/main/kotlin/com/msg/gcms/domain/user/domain/entity/User.kt
  src/main/resources/application.yml
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#96 🔀 :: 95 - 동아리 리스트 반환값 수정
  src/main/kotlin/com/msg/gcms/domain/user/utils/impl/UserConverterImpl.kt
Labels: 2️⃣ Priority: Medium, 🐞 Bug

#94 🔀 :: cors 문제 해결
  src/main/kotlin/com/msg/gcms/global/web/WebMvcConfig.kt
Labels: ⚙ Setting

#102 🔀 :: 101 동아리 디테일 페이지 permitAll로 수정
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/DetailClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
  src/main/kotlin/com/msg/gcms/global/util/UserUtil.kt
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#104 🔀 :: 103 동아리 수정시 clubType 안받게 수정
  src/main/kotlin/com/msg/gcms/domain/club/presentation/data/dto/UpdateClubDto.kt
  src/main/kotlin/com/msg/gcms/domain/club/presentation/data/request/UpdateClubRequest.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/UpdateClubService.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/UpdateClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/utils/ClubConverter.kt
  src/main/kotlin/com/msg/gcms/domain/club/utils/SaveClubUtil.kt
  src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt
  src/test/kotlin/com/msg/gcms/domain/club/controller/UpdateClubControllerTest.kt
  src/test/kotlin/com/msg/gcms/domain/club/service/UpdateClubServiceImplTest.kt
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#106 🔀 :: 105 - 유저 검색에 본인이 나오지않도록 수정
  src/main/kotlin/com/msg/gcms/domain/user/service/impl/SearchUserServiceImpl.kt
  src/test/kotlin/com/msg/gcms/domain/user/service/SearchUserServiceTest.kt
Labels: 1️⃣ Priority: High, 🐞 Bug

#108 🔀 :: 101-서버의 시간을 서울로 기본세팅하였습니다.
  src/main/kotlin/com/msg/gcms/GcmsApplication.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#110 🔀 cors origin 추가
  src/main/kotlin/com/msg/gcms/global/web/WebMvcConfig.kt
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#116 🔀 :: 115- 반환값에 사용된 함수 변경
  src/main/kotlin/com/msg/gcms/domain/applicant/presentation/ApplicantController.kt
Labels: 1️⃣ Priority: High, 🐞 Bug

#114 🔀 :: 111-동아리 수정하면 복사되는 버그
  src/main/kotlin/com/msg/gcms/domain/club/utils/impl/ClubConverterImpl.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#112 🔀 :: 109-자율/전공 동아리 부장혹은 구성원일때 동아리를 생성하지 못하도록 수정
  src/main/kotlin/com/msg/gcms/domain/club/exception/AlreadyClubHeadException.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#120 🔀 :: 119-동아리 구성원에 부장이 들어있는지 확인하는 로직 추가
  src/main/kotlin/com/msg/gcms/domain/club/utils/SaveClubUtil.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor, 🐞 Bug
