Repository GSM-MSG/GCMS-BackEnd, pull requests merged in 2024-04, with the labels that each got.

#320 code owners 변경
  .github/CODEOWNERS
Labels: 3️⃣ Priority: Low

#318 🔀 :: 314 공지사항 상세 조회 API
  src/main/kotlin/com/msg/gcms/domain/notice/presentation/NoticeController.kt
  src/main/kotlin/com/msg/gcms/domain/notice/presentation/data/response/FindNoticeDetailResponseDto.kt
  src/main/kotlin/com/msg/gcms/domain/notice/service/FindNoticeDetailService.kt
  src/main/kotlin/com/msg/gcms/domain/notice/service/impl/FindNoticeDetailServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/notice/utils/NoticeConverter.kt
  src/main/kotlin/com/msg/gcms/domain/notice/utils/impl/NoticeConverterImpl.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#324 🔀 :: new pull request template 적용
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙ Setting, ⚡️ Simple

#327 요청한 날짜와 교시에 이미 스케쥴이 존재하면 예외 발생
  src/main/kotlin/com/msg/gcms/domain/attendance/exception/AlreadyScheduleExistException.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/request/CreateScheduleRequestDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/CustomScheduleRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/impl/CustomScheduleRepositoryImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/CreateScheduleServiceImpl.kt
  src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
Labels: 1️⃣ Priority: High

#329 delete :: print function
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/DetailClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/global/util/UserUtil.kt
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#331 🔀 :: 330 로그인 API 리팩토링
  src/main/kotlin/com/msg/gcms/domain/auth/service/impl/SignInServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/auth/util/AuthConverter.kt
  src/main/kotlin/com/msg/gcms/domain/auth/util/AuthUtil.kt
  src/main/kotlin/com/msg/gcms/domain/auth/util/impl/AuthConverterImpl.kt
  src/main/kotlin/com/msg/gcms/domain/auth/util/impl/AuthUtilImpl.kt
  src/test/kotlin/com/msg/gcms/domain/auth/service/SignInServiceTest.kt
Labels: 3️⃣ Priority: Low, ♻️ Refactor

#332 출석부 중복 생성 예외 pr에 빠진 코드리뷰 반영
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/CustomScheduleRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/impl/CustomScheduleRepositoryImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/CreateScheduleServiceImpl.kt
Labels: 1️⃣ Priority: High

#336 🔀 :: 출석 상태 변경 API 오타 수정
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#338 🔀 :: resolve nonUniqueResultException Schedule entity
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/ScheduleRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/CreateScheduleServiceImpl.kt
Labels: 0️⃣ Priority: Critical

#340 🔀 :: rowNum +연산 위치 변경
  src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/ClubAttendanceStatusExcelServiceImpl.kt
Labels: 0️⃣ Priority: Critical

#342 🔀 :: 선생님 동아리 수정 권한 삭제
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/UpdateClubServiceImpl.kt
Labels: 0️⃣ Priority: Critical

#344 🔀 :: exist by club condition 추가
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/CustomScheduleRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/CreateScheduleServiceImpl.kt
Labels: 0️⃣ Priority: Critical

#346 🔀 :: custom repository condition
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/impl/CustomScheduleRepositoryImpl.kt
Labels: 0️⃣ Priority: Critical

#348 🔀 :: 자신의 출석 상태 조회
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/AttendanceController.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/response/AttendSelfCheckResponseDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/AttendanceRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/QueryCurrentAttendStatusService.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/QueryCurrentAttendStatusServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/AttendanceConverter.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/impl/AttendanceConverterImpl.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
Labels: ✨ Feature
