Repository GSM-MSG/GCMS-BackEnd, pull requests merged in 2024-03, with the labels that each got.

#274 🔀 :: healthcheck API
  src/main/kotlin/com/msg/gcms/domain/health/presentation/HealthCheckController.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
Labels: 🌏 Deploy

#276 🔀 :: 275 출석 체크 엔티티 세팅
  src/main/kotlin/com/msg/gcms/domain/attendance/domain/entity/Attendance.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/domain/entity/Schedule.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/domain/enums/AttendanceStatus.kt
Labels: 1️⃣ Priority: High

#278 🔀 :: 동아리 출석부 생성 api
  src/main/kotlin/com/msg/gcms/domain/attendance/domain/entity/Schedule.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/domain/enums/AttendanceStatus.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/AttendanceController.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/dto/ScheduleDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/request/CreateScheduleRequestDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/AttendanceRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/ScheduleRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/CreateScheduleService.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/CreateScheduleServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/AttendanceConverter.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/ScheduleConverter.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/impl/AttendanceConverterImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/impl/ScheduleConverterImpl.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
Labels: 0️⃣ Priority: Critical

#283 출석 상태 변경 api를 작성했습니다.
  src/main/kotlin/com/msg/gcms/domain/applicant/service/impl/AcceptApplicantServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/applicant/service/impl/ApplicantListServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/applicant/service/impl/CancelApplicationServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/applicant/service/impl/ClubApplyServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/applicant/service/impl/RejectApplicantServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/exception/AttendanceNotFoundException.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/exception/ScheduleNotFoundException.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/AttendanceController.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/dto/AttendanceStatusDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/request/UpdateAttendanceStatusRequestDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/AttendanceRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/UpdateAttendanceStatusService.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/CreateScheduleServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/UpdateAttendanceStatusServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/AttendanceConverter.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/impl/AttendanceConverterImpl.kt
  src/main/kotlin/com/msg/gcms/domain/auth/service/impl/GetNewRefreshTokenServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/auth/service/impl/LogoutServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/auth/service/impl/SignInServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/CloseClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateOpeningApplicationServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/CreateOperationPlanServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/DeleteClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/DetailClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/ExitClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/FindClubListServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/OpenClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/service/impl/UpdateClubServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/service/impl/DelegateHeadServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/service/impl/ExitClubMemberServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/clubMember/service/impl/FindClubMemberListServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/image/service/impl/UploadImageServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/user/service/impl/FindUserProfileServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/user/service/impl/FindUserServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/user/service/impl/SearchUserServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/user/service/impl/UpdateProfileImgServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/user/service/impl/WithdrawUserServiceImpl.kt
  src/main/kotlin/com/msg/gcms/global/annotation/ServiceWithReadOnlyTransaction.kt
  src/main/kotlin/com/msg/gcms/global/annotation/ServiceWithTransaction.kt
  src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#285 🔀 :: 동아리 출석 체크 현황 조회 API
  src/main/kotlin/com/msg/gcms/domain/attendance/exception/ScheduleNotFoundException.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/AttendanceController.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/dto/SearchScheduleDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/dto/UserAttendanceStatusListDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/AttendanceRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/CustomScheduleRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/ScheduleRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/impl/CustomScheduleRepositoryImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/QueryCurrentAttendConditionService.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/QueryCurrentAttendConditionServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/AttendanceConverter.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/ScheduleConverter.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/impl/AttendanceConverterImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/impl/ScheduleConverterImpl.kt
  src/main/kotlin/com/msg/gcms/domain/club/exception/HeadNotSameException.kt
  src/main/kotlin/com/msg/gcms/global/exception/ErrorCode.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#289 Schedule의 period의 위치를 Attendance로 변경
  src/main/kotlin/com/msg/gcms/domain/attendance/domain/entity/Attendance.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/domain/entity/Schedule.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/AttendanceController.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/dto/AttendanceDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/dto/ScheduleDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/dto/UserAttendanceStatusListDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/request/UpdateAttendanceStatusBatchRequestDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/request/UpdateAttendanceStatusRequestDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/AttendanceRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/CustomAttendanceRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/CustomScheduleRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/impl/CustomAttendanceRepositoryImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/impl/CustomScheduleRepositoryImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/CreateScheduleServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/QueryCurrentAttendConditionServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/UpdateAttendanceStatusBatchServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/UpdateAttendanceStatusServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/AttendanceConverter.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/ScheduleConverter.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/impl/AttendanceConverterImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/impl/ScheduleConverterImpl.kt
Labels: 1️⃣ Priority: High

#291 period 타입을 LocalTime에서 Enum으로 변경했습니다.
  src/main/kotlin/com/msg/gcms/domain/attendance/domain/entity/Attendance.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/domain/enums/AttendanceStatus.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/domain/enums/Period.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/AttendanceController.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/dto/ScheduleDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/dto/SearchScheduleDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/request/CreateScheduleRequestDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/AttendanceRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/CustomAttendanceRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/impl/CustomAttendanceRepositoryImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/QueryCurrentAttendConditionServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/AttendanceConverter.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/ScheduleConverter.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/impl/AttendanceConverterImpl.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/impl/ScheduleConverterImpl.kt
Labels: 1️⃣ Priority: High

#294 Period enum 오타를 수정했습니다
  src/main/kotlin/com/msg/gcms/domain/attendance/domain/enums/Period.kt
Labels: 0️⃣ Priority: Critical

#292 🔀 :: 287 출석부 엑셀 출력 API
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/AttendanceController.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/AttendanceRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/repository/ScheduleRepository.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/ClubAttendanceStatusExcelService.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/service/impl/ClubAttendanceStatusExcelServiceImpl.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
  src/main/resources/logs/access-2024-03-22.0.log
  src/main/resources/logs/error-2024-03-22.0.log
Labels: 1️⃣ Priority: High, ✨ Feature

#296 공지사항 도메인을 세팅했습니다.
  src/main/kotlin/com/msg/gcms/domain/notice/domain/entity/Notice.kt
  src/main/kotlin/com/msg/gcms/domain/notice/domain/repository/NoticeRepository.kt
Labels: 2️⃣ Priority: Medium, ⚙ Setting

#272 Ops codedeploy
  .github/workflows/GCMS-CD.yml
  Dockerfile
  appspec.yml
  scripts/start.sh
Labels: 🌏 Deploy

#300 공지사항 작성 api를 개발했습니다
  src/main/kotlin/com/msg/gcms/domain/notice/domain/entity/Notice.kt
  src/main/kotlin/com/msg/gcms/domain/notice/presentation/NoticeController.kt
  src/main/kotlin/com/msg/gcms/domain/notice/presentation/data/dto/NoticeDto.kt
  src/main/kotlin/com/msg/gcms/domain/notice/presentation/data/request/CreateNoticeRequestDto.kt
  src/main/kotlin/com/msg/gcms/domain/notice/service/CreateNoticeService.kt
  src/main/kotlin/com/msg/gcms/domain/notice/service/impl/CreateNoticeServiceImpl.kt
  src/main/kotlin/com/msg/gcms/domain/notice/utils/NoticeConverter.kt
  src/main/kotlin/com/msg/gcms/domain/notice/utils/impl/NoticeConverterImpl.kt
  src/main/kotlin/com/msg/gcms/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#302 🔀 :: 학생 출석 현황 조회 response parameter id -> uuid
  src/main/kotlin/com/msg/gcms/domain/attendance/presentation/data/dto/UserAttendanceStatusListDto.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/AttendanceConverter.kt
  src/main/kotlin/com/msg/gcms/domain/attendance/util/impl/AttendanceConverterImpl.kt
Labels: ⚡️ Simple

#304 🔀 :: 303 cicd 워크플로 작성
  .github/workflows/GCMS-CD.yml
  .github/workflows/GCMS-CI.yml
  appspec.yml
  deploy.sh
  docker-compose.yml
  src/main/resources/logs/access-2024-03-22.0.log
  src/main/resources/logs/error-2024-03-22.0.log
Labels: 🌏 Deploy

#306 🔀 :: cd 경로 수정
  appspec.yml
  deploy.sh
Labels: 🌏 Deploy

#308 🔀 :: application.yml overwrite
  .github/workflows/GCMS-CD.yml
Labels: ⚡️ Simple, 🌏 Deploy

#311 🔀 :: gcms from vercel domain cors
  src/main/kotlin/com/msg/gcms/global/web/WebMvcConfig.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple
